/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package diceGame;

/**
 *
 * @author evrob0095
 */
public class diceGame extends javax.swing.JFrame {

    /**
     * Creates new form diceGame
     */
    public diceGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        instructionsLabel2 = new javax.swing.JLabel();
        instructionsLabel1 = new javax.swing.JLabel();
        guessLabel = new javax.swing.JLabel();
        guessInput = new javax.swing.JTextField();
        rollButton = new javax.swing.JButton();
        diceRollLabel = new javax.swing.JLabel();
        diceRollLabel1 = new javax.swing.JLabel();
        instructionsLabel3 = new javax.swing.JLabel();
        instructionsLabel4 = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        diceComboBox = new javax.swing.JComboBox();
        luckyButton = new javax.swing.JButton();
        percentCorrectGuessesLabel = new javax.swing.JLabel();
        numberRollsLabel = new javax.swing.JLabel();
        correctGuessesLabel = new javax.swing.JLabel();
        incorrectGuessesLabel = new javax.swing.JLabel();
        numberPercentCorrectGuessLabel = new javax.swing.JLabel();
        rollNumberLabel = new javax.swing.JLabel();
        numberCorrectGuessLabel = new javax.swing.JLabel();
        numberIncorrectGuessLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(255, 204, 0));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructionsLabel2.setFont(new java.awt.Font("WebLetterer Pro BB", 0, 18)); // NOI18N
        instructionsLabel2.setText("largest possible value of the dice");
        panel.add(instructionsLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, 20));

        instructionsLabel1.setFont(new java.awt.Font("WebLetterer Pro BB", 0, 18)); // NOI18N
        instructionsLabel1.setText("Choose which kind of dice you want to roll");
        panel.add(instructionsLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        guessLabel.setFont(new java.awt.Font("WebLetterer Pro BB", 0, 18)); // NOI18N
        guessLabel.setText("Your Guess");
        panel.add(guessLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 20));

        guessInput.setFont(new java.awt.Font("WebLetterer Pro BB", 0, 14)); // NOI18N
        panel.add(guessInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 80, 30));

        rollButton.setFont(new java.awt.Font("WebLetterer Pro BB", 0, 11)); // NOI18N
        rollButton.setText("Roll The Dice!");
        rollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollButtonActionPerformed(evt);
            }
        });
        panel.add(rollButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 160, 30));

        diceRollLabel.setFont(new java.awt.Font("WebLetterer Pro BB", 0, 18)); // NOI18N
        diceRollLabel.setText("Dice Roll");
        panel.add(diceRollLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, 20));

        diceRollLabel1.setFont(new java.awt.Font("WebLetterer Pro BB", 0, 18)); // NOI18N
        diceRollLabel1.setForeground(new java.awt.Color(0, 0, 255));
        diceRollLabel1.setText("0");
        panel.add(diceRollLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, 20));

        instructionsLabel3.setFont(new java.awt.Font("WebLetterer Pro BB", 0, 18)); // NOI18N
        instructionsLabel3.setText("Then click roll to roll the dice");
        panel.add(instructionsLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, 20));

        instructionsLabel4.setFont(new java.awt.Font("WebLetterer Pro BB", 0, 18)); // NOI18N
        instructionsLabel4.setText("Then enter a number between 1 and the");
        panel.add(instructionsLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, 20));

        titleLabel.setFont(new java.awt.Font("Vademecum", 0, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 204, 204));
        titleLabel.setText("Designless Dice Diversion");
        titleLabel.setToolTipText("");
        panel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        diceComboBox.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        diceComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Coin (2 Sided)", "D4 (4 Sided)", "Regular Dice (6 Sided)", "D20 (20 Sided)", "Basically a sphere (120 Sided)" }));
        diceComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                diceComboBoxItemStateChanged(evt);
            }
        });
        diceComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diceComboBoxActionPerformed(evt);
            }
        });
        panel.add(diceComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        luckyButton.setFont(new java.awt.Font("WebLetterer Pro BB", 0, 8)); // NOI18N
        luckyButton.setText("I'm Feeling Lucky");
        luckyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luckyButtonActionPerformed(evt);
            }
        });
        panel.add(luckyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 140, 20));

        percentCorrectGuessesLabel.setFont(new java.awt.Font("WebLetterer Pro BB", 0, 18)); // NOI18N
        percentCorrectGuessesLabel.setText("Percentage of Correct Guesses:");
        panel.add(percentCorrectGuessesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, 20));

        numberRollsLabel.setFont(new java.awt.Font("WebLetterer Pro BB", 0, 18)); // NOI18N
        numberRollsLabel.setText("Number of Rolls:");
        panel.add(numberRollsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 20));

        correctGuessesLabel.setFont(new java.awt.Font("WebLetterer Pro BB", 0, 18)); // NOI18N
        correctGuessesLabel.setText("Correct Guesses:");
        panel.add(correctGuessesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, 20));

        incorrectGuessesLabel.setFont(new java.awt.Font("WebLetterer Pro BB", 0, 18)); // NOI18N
        incorrectGuessesLabel.setText("Incorrect Guesses:");
        panel.add(incorrectGuessesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, 20));

        numberPercentCorrectGuessLabel.setFont(new java.awt.Font("WebLetterer Pro BB", 0, 18)); // NOI18N
        numberPercentCorrectGuessLabel.setForeground(new java.awt.Color(0, 0, 255));
        numberPercentCorrectGuessLabel.setText("0");
        panel.add(numberPercentCorrectGuessLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, 20));

        rollNumberLabel.setFont(new java.awt.Font("WebLetterer Pro BB", 0, 18)); // NOI18N
        rollNumberLabel.setForeground(new java.awt.Color(0, 0, 255));
        rollNumberLabel.setText("0");
        panel.add(rollNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, 20));

        numberCorrectGuessLabel.setFont(new java.awt.Font("WebLetterer Pro BB", 0, 18)); // NOI18N
        numberCorrectGuessLabel.setForeground(new java.awt.Color(0, 0, 255));
        numberCorrectGuessLabel.setText("0");
        panel.add(numberCorrectGuessLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, 20));

        numberIncorrectGuessLabel.setFont(new java.awt.Font("WebLetterer Pro BB", 0, 18)); // NOI18N
        numberIncorrectGuessLabel.setForeground(new java.awt.Color(0, 0, 255));
        numberIncorrectGuessLabel.setText("0");
        panel.add(numberIncorrectGuessLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, 20));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diceComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diceComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diceComboBoxActionPerformed

    private void luckyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luckyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luckyButtonActionPerformed

    private void rollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollButtonActionPerformed
        
        //Variables
        int guess;
        int diceRoll = 0;
        int numberRolls = 0;
        int correctGuesses = 0;
        int incorrectGuesses = 0;
        int percCorrectGuesses = 0;
        
        
        
        String comboBox = (String)diceComboBox.getSelectedItem();
        if  (comboBox.equals("Coin (2 Sided)")) {
            diceRoll = (int)Math.round(Math.random()*1+1);
            diceRollLabel1.setText(""+diceRoll);     
        }
        else if (comboBox.equals("D4 (4 Sided)")) {
            diceRoll = (int)Math.round(Math.random()*3+1);
            diceRollLabel1.setText(""+diceRoll);
        }
        else if (comboBox.equals("Regular Dice (6 Sided)")) {
            diceRoll = (int)Math.round(Math.random()*5+1);
            diceRollLabel1.setText(""+diceRoll);
        }
        else if (comboBox.equals("D20 (20 Sided)")) {
            diceRoll = (int)Math.round(Math.random()*19+1);
            diceRollLabel1.setText(""+diceRoll);
        }
        else if (comboBox.equals("Basically a sphere (120 Sided)")) {
            diceRoll = (int)Math.round(Math.random()*119+1);
            diceRollLabel1.setText(""+diceRoll);
        }
        
        guess = Integer.parseInt(guessInput.getText());
        
        if (guess == diceRoll) {
            numberRolls = numberRolls + 1;
            correctGuesses = correctGuesses + 1;
            percCorrectGuesses = (correctGuesses/numberRolls)*100;
            
            rollNumberLabel.setText("" + numberRolls);
            numberCorrectGuessLabel.setText("" + correctGuesses);
            numberPercentCorrectGuessLabel.setText("" + percCorrectGuesses);
            
        }
        else if (guess != diceRoll) {
            numberRolls = numberRolls + 1;
            incorrectGuesses = incorrectGuesses + 1;
            percCorrectGuesses = (correctGuesses/numberRolls)*100;
            
            rollNumberLabel.setText("" + numberRolls);
            numberIncorrectGuessLabel.setText("" + incorrectGuesses);
            numberPercentCorrectGuessLabel.setText("" + percCorrectGuesses);
        }
        
        
    }//GEN-LAST:event_rollButtonActionPerformed

    private void diceComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_diceComboBoxItemStateChanged
        
    }//GEN-LAST:event_diceComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new diceGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel correctGuessesLabel;
    private javax.swing.JComboBox diceComboBox;
    private javax.swing.JLabel diceRollLabel;
    private javax.swing.JLabel diceRollLabel1;
    private javax.swing.JTextField guessInput;
    private javax.swing.JLabel guessLabel;
    private javax.swing.JLabel incorrectGuessesLabel;
    private javax.swing.JLabel instructionsLabel1;
    private javax.swing.JLabel instructionsLabel2;
    private javax.swing.JLabel instructionsLabel3;
    private javax.swing.JLabel instructionsLabel4;
    private javax.swing.JButton luckyButton;
    private javax.swing.JLabel numberCorrectGuessLabel;
    private javax.swing.JLabel numberIncorrectGuessLabel;
    private javax.swing.JLabel numberPercentCorrectGuessLabel;
    private javax.swing.JLabel numberRollsLabel;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel percentCorrectGuessesLabel;
    private javax.swing.JButton rollButton;
    private javax.swing.JLabel rollNumberLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
